apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-33-tenant/load-app-4414064a-65aa-45ec-a7a4-970ccfbe2dae/devfile-sample-go-basic@sha256:8d427cd86c614d661cc144ef4a163af63b948e12f24a31645094055a42785acd
        name: my-go
        resources: {}
status: {}
